CREATE TABLE
IF NOT EXISTS UTILISATEURS
(
    id INT
    AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR
(100) NOT NULL,
    prenom VARCHAR
(100) NOT NULL,
    email VARCHAR
(255) UNIQUE NOT NULL,
    mot_de_passe VARCHAR
(255) NOT NULL,
    date_inscription DATE NOT NULL,
    role VARCHAR
(50) NOT NULL
);

CREATE TABLE
IF NOT EXISTS CATEGORIES
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR
(100) NOT NULL
);

CREATE TABLE
IF NOT EXISTS FILMS
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR
(255) NOT NULL,
    synopsis TEXT,
    date_sortie DATE,
    image VARCHAR
(255),
    notation FLOAT,
    critique TEXT
);

CREATE TABLE
IF NOT EXISTS FILMS_CATEGORIES
(
    film_id INT NOT NULL,
    categorie_id INT NOT NULL,
    PRIMARY KEY
(film_id, categorie_id),
    FOREIGN KEY
(film_id) REFERENCES FILMS
(id) ON
DELETE CASCADE,
    FOREIGN KEY (categorie_id)
REFERENCES CATEGORIES
(id) ON
DELETE CASCADE
);

CREATE TABLE
IF NOT EXISTS FAVORIS
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    utilisateur_id INT NOT NULL,
    film_id INT NOT NULL,
    liste_numero TINYINT NOT NULL,
    FOREIGN KEY
(utilisateur_id) REFERENCES UTILISATEURS
(id),
    FOREIGN KEY
(film_id) REFERENCES FILMS
(id)
);

CREATE TABLE
IF NOT EXISTS VISIONNES
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    utilisateur_id INT NOT NULL,
    film_id INT NOT NULL,
    liste_numero TINYINT NOT NULL,
    date_visionnage DATE NOT NULL,
    FOREIGN KEY
(utilisateur_id) REFERENCES UTILISATEURS
(id),
    FOREIGN KEY
(film_id) REFERENCES FILMS
(id)
);

CREATE TABLE
IF NOT EXISTS LISTES
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    utilisateur_id INT NOT NULL,
    nom VARCHAR
(255) NOT NULL,
    type VARCHAR
(50),
    FOREIGN KEY
(utilisateur_id) REFERENCES UTILISATEURS
(id)
);

CREATE TABLE
IF NOT EXISTS FILMS_LISTES
(
    id INT
    AUTO_INCREMENT PRIMARY KEY,
    liste_id INT NOT NULL,
    film_id INT NOT NULL,
    date_ajout DATE NOT NULL,
    FOREIGN KEY
(liste_id) REFERENCES LISTES
(id),
    FOREIGN KEY
(film_id) REFERENCES FILMS
(id)
);
